export const mockInfluencers = [
  {
    id: "inf-1",
    name: "Sarah Chen",
    platform: "YouTube",
    platformIcon: "🎬",
    handle: "@sarahcreates",
    followers: 245000,
    topics: ["content strategy", "creator economy", "social media marketing"],
    avgViews: 18500,
    avgEngagement: 4.2,
    avatarUrl: null,
    bio: "Teaching creators how to build sustainable businesses. 5 years in the creator economy.",
  },
  {
    id: "inf-2",
    name: "Marcus Rivera",
    platform: "TikTok",
    platformIcon: "🎵",
    handle: "@marcusrivera",
    followers: 890000,
    topics: ["content creation", "video editing", "storytelling"],
    avgViews: 125000,
    avgEngagement: 6.8,
    avatarUrl: null,
    bio: "Video editor turned creator. Helping you tell better stories in 60 seconds.",
  },
  {
    id: "inf-3",
    name: "Alex Thompson",
    platform: "Instagram",
    platformIcon: "📸",
    handle: "@alexthompson",
    followers: 156000,
    topics: ["personal branding", "content strategy", "instagram growth"],
    avgViews: 32000,
    avgEngagement: 3.9,
    avatarUrl: null,
    bio: "Brand strategist. Grew 3 brands from 0 to 100K. Sharing what works.",
  },
  {
    id: "inf-4",
    name: "Jamie Okafor",
    platform: "LinkedIn",
    platformIcon: "💼",
    handle: "jamie-okafor",
    followers: 52000,
    topics: ["b2b content", "thought leadership", "linkedin growth"],
    avgViews: 8500,
    avgEngagement: 5.1,
    avatarUrl: null,
    bio: "B2B content that doesn't put people to sleep. VP Marketing turned creator coach.",
  },
  {
    id: "inf-5",
    name: "Priya Sharma",
    platform: "Substack",
    platformIcon: "📝",
    handle: "priya-writes",
    followers: 28000,
    topics: ["newsletter growth", "writing", "creator tools"],
    avgViews: 4200,
    avgEngagement: 7.3,
    avatarUrl: null,
    bio: "Writing about writing. 28K subscribers in 18 months. No shortcuts.",
  },
  {
    id: "inf-6",
    name: "David Kim",
    platform: "Facebook",
    platformIcon: "👤",
    handle: "davidkimcreator",
    followers: 340000,
    topics: ["community building", "facebook groups", "creator monetization"],
    avgViews: 45000,
    avgEngagement: 3.2,
    avatarUrl: null,
    bio: "Built a 200K member community on Facebook. Teaching group growth strategies.",
  },
];

// Detailed creator profiles for Research drill-down
export const mockCreatorDetails: Record<string, {
  postsPerWeek: number;
  audienceSplit: { label: string; pct: number }[];
  growthRate: string;
  topContent: { title: string; views: number; likes: number; date: string }[];
  contentMix: { type: string; pct: number }[];
  peakPostingTime: string;
  avgPostFrequency: string;
  nicheFit: string;
}> = {
  "inf-1": {
    postsPerWeek: 3,
    audienceSplit: [{ label: "18-24", pct: 22 }, { label: "25-34", pct: 45 }, { label: "35-44", pct: 23 }, { label: "45+", pct: 10 }],
    growthRate: "+8.2% / month",
    topContent: [
      { title: "How I Built a 6-Figure Creator Business", views: 142000, likes: 9800, date: "2026-05-12" },
      { title: "Creator Economy 2026: What's Changed", views: 89000, likes: 6200, date: "2026-04-28" },
      { title: "5 Revenue Streams Every Creator Needs", views: 67000, likes: 4100, date: "2026-05-22" },
    ],
    contentMix: [{ type: "Long-form video", pct: 60 }, { type: "Shorts", pct: 25 }, { type: "Community posts", pct: 15 }],
    peakPostingTime: "Tuesdays & Thursdays, 2-4 PM EST",
    avgPostFrequency: "3 videos/week, 5 community posts/week",
    nicheFit: "Strong alignment with creator education vertical. High-quality production, consistent schedule.",
  },
  "inf-2": {
    postsPerWeek: 7,
    audienceSplit: [{ label: "13-17", pct: 18 }, { label: "18-24", pct: 52 }, { label: "25-34", pct: 24 }, { label: "35+", pct: 6 }],
    growthRate: "+15.4% / month",
    topContent: [
      { title: "Edit like a pro in 30 seconds", views: 2100000, likes: 180000, date: "2026-05-30" },
      { title: "POV: Your first viral video", views: 890000, likes: 72000, date: "2026-06-02" },
      { title: "3 transitions that change everything", views: 650000, likes: 54000, date: "2026-05-18" },
    ],
    contentMix: [{ type: "Tutorial", pct: 45 }, { type: "Trend/meme", pct: 30 }, { type: "Behind the scenes", pct: 25 }],
    peakPostingTime: "Daily, 6-8 PM EST",
    avgPostFrequency: "1-2 videos/day",
    nicheFit: "Excellent for video editing niche. High virality, young audience, strong trend adoption.",
  },
  "inf-3": {
    postsPerWeek: 5,
    audienceSplit: [{ label: "18-24", pct: 28 }, { label: "25-34", pct: 42 }, { label: "35-44", pct: 20 }, { label: "45+", pct: 10 }],
    growthRate: "+4.8% / month",
    topContent: [
      { title: "Your brand is not your logo (carousel)", views: 85000, likes: 7200, date: "2026-05-20" },
      { title: "I audited 100 creator profiles", views: 62000, likes: 5100, date: "2026-06-01" },
      { title: "Reel: Brand voice in 15 seconds", views: 120000, likes: 9800, date: "2026-05-25" },
    ],
    contentMix: [{ type: "Carousel", pct: 40 }, { type: "Reels", pct: 35 }, { type: "Stories", pct: 25 }],
    peakPostingTime: "Mon/Wed/Fri, 11 AM EST",
    avgPostFrequency: "5 posts/week, daily stories",
    nicheFit: "Strong branding expertise. Carousel content performs well for educational format.",
  },
  "inf-4": {
    postsPerWeek: 4,
    audienceSplit: [{ label: "25-34", pct: 35 }, { label: "35-44", pct: 38 }, { label: "45-54", pct: 20 }, { label: "55+", pct: 7 }],
    growthRate: "+6.1% / month",
    topContent: [
      { title: "The LinkedIn algorithm rewards this one thing", views: 45000, likes: 3200, date: "2026-05-15" },
      { title: "I got 10M impressions. Here's what I learned.", views: 38000, likes: 2800, date: "2026-06-03" },
      { title: "Stop writing LinkedIn posts like emails", views: 29000, likes: 2100, date: "2026-05-28" },
    ],
    contentMix: [{ type: "Text post", pct: 55 }, { type: "Document/PDF", pct: 25 }, { type: "Video", pct: 20 }],
    peakPostingTime: "Tue-Thu, 8-9 AM EST",
    avgPostFrequency: "4 posts/week",
    nicheFit: "B2B thought leadership. Older professional audience, high engagement rate for the platform.",
  },
  "inf-5": {
    postsPerWeek: 2,
    audienceSplit: [{ label: "25-34", pct: 40 }, { label: "35-44", pct: 35 }, { label: "45+", pct: 25 }],
    growthRate: "+3.2% / month",
    topContent: [
      { title: "Why I stopped chasing subscribers", views: 12000, likes: 890, date: "2026-05-20" },
      { title: "The tools I actually use to write", views: 8500, likes: 620, date: "2026-06-05" },
      { title: "Newsletter growth is dead. Long live newsletters.", views: 15000, likes: 1100, date: "2026-04-30" },
    ],
    contentMix: [{ type: "Long-form essay", pct: 60 }, { type: "Quick take", pct: 25 }, { type: "Resource list", pct: 15 }],
    peakPostingTime: "Sundays, 10 AM EST",
    avgPostFrequency: "2 newsletters/week",
    nicheFit: "Deep writing expertise. Smaller but highly engaged audience. High open rates.",
  },
  "inf-6": {
    postsPerWeek: 6,
    audienceSplit: [{ label: "25-34", pct: 30 }, { label: "35-44", pct: 35 }, { label: "45-54", pct: 25 }, { label: "55+", pct: 10 }],
    growthRate: "+2.9% / month",
    topContent: [
      { title: "How I grew my Facebook group to 200K", views: 120000, likes: 8500, date: "2026-05-10" },
      { title: "Live Q&A: Group monetization strategies", views: 45000, likes: 3200, date: "2026-06-01" },
      { title: "The death of organic reach (and what to do)", views: 67000, likes: 4800, date: "2026-05-22" },
    ],
    contentMix: [{ type: "Video", pct: 40 }, { type: "Text post", pct: 35 }, { type: "Live stream", pct: 25 }],
    peakPostingTime: "Daily, varies",
    avgPostFrequency: "1 post/day + 2 lives/week",
    nicheFit: "Community building authority. Strong for group-based creator programs.",
  },
};

export const trendingTopics = [
  { topic: "AI-generated content", growth: "+340%", platforms: ["TikTok", "YouTube", "LinkedIn"], postsThisWeek: 12400 },
  { topic: "Creator monetization", growth: "+89%", platforms: ["YouTube", "Substack", "Instagram"], postsThisWeek: 8200 },
  { topic: "Short-form storytelling", growth: "+125%", platforms: ["TikTok", "Instagram", "YouTube"], postsThisWeek: 45000 },
  { topic: "Personal branding", growth: "+56%", platforms: ["LinkedIn", "Instagram", "TikTok"], postsThisWeek: 6800 },
  { topic: "Newsletter growth", growth: "+72%", platforms: ["Substack", "LinkedIn"], postsThisWeek: 3200 },
  { topic: "Community-led growth", growth: "+93%", platforms: ["Facebook", "Discord", "YouTube"], postsThisWeek: 4100 },
  { topic: "Video editing tutorials", growth: "+210%", platforms: ["TikTok", "YouTube"], postsThisWeek: 18900 },
  { topic: "Creator burnout", growth: "+145%", platforms: ["YouTube", "Substack", "LinkedIn"], postsThisWeek: 2800 },
];

export const mockConnectedAccounts = [
  { id: "acc-1", platform: "YouTube", platformIcon: "🎬", handle: "@bedford-demo", status: "connected", followers: 1250 },
  { id: "acc-2", platform: "Instagram", platformIcon: "📸", handle: "@bedford.demo", status: "connected", followers: 3400 },
  { id: "acc-3", platform: "TikTok", platformIcon: "🎵", handle: "@bedforddemo", status: "connected", followers: 780 },
  { id: "acc-4", platform: "Facebook", platformIcon: "👤", handle: "Bedford Demo Page", status: "connected", followers: 2100 },
];

export const mockPosts = [
  {
    id: "post-1",
    title: "5 Tips for Growing Your Creator Business",
    platform: "YouTube",
    platformIcon: "🎬",
    publishedAt: "2026-06-01T14:00:00Z",
    type: "VIDEO",
    engagement: { views: 12400, likes: 890, comments: 156, shares: 0 },
  },
  {
    id: "post-2",
    title: "Behind the scenes of our content workshop",
    platform: "Instagram",
    platformIcon: "📸",
    publishedAt: "2026-06-03T10:30:00Z",
    type: "POST",
    engagement: { views: 8200, likes: 1240, comments: 89, shares: 234 },
  },
  {
    id: "post-3",
    title: "Creator tools you need in 2026",
    platform: "TikTok",
    platformIcon: "🎵",
    publishedAt: "2026-06-05T16:00:00Z",
    type: "VIDEO",
    engagement: { views: 45600, likes: 3200, comments: 412, shares: 1890 },
  },
  {
    id: "post-4",
    title: "How we train the next generation of creators",
    platform: "Facebook",
    platformIcon: "👤",
    publishedAt: "2026-06-02T09:00:00Z",
    type: "POST",
    engagement: { views: 3400, likes: 245, comments: 67, shares: 0 },
  },
  {
    id: "post-5",
    title: "The creator economy is broken. Here's how we fix it.",
    platform: "YouTube",
    platformIcon: "🎬",
    publishedAt: "2026-05-28T12:00:00Z",
    type: "VIDEO",
    engagement: { views: 28900, likes: 2100, comments: 389, shares: 0 },
  },
  {
    id: "post-6",
    title: "Day in the life of a content creator student",
    platform: "Instagram",
    platformIcon: "📸",
    publishedAt: "2026-06-07T11:00:00Z",
    type: "REELS",
    engagement: { views: 15300, likes: 2890, comments: 201, shares: 567 },
  },
  {
    id: "post-7",
    title: "What nobody tells you about going viral",
    platform: "TikTok",
    platformIcon: "🎵",
    publishedAt: "2026-06-08T15:30:00Z",
    type: "VIDEO",
    engagement: { views: 92300, likes: 8400, comments: 1230, shares: 4500 },
  },
  {
    id: "post-8",
    title: "Community AMA: Ask our top creators anything",
    platform: "Facebook",
    platformIcon: "👤",
    publishedAt: "2026-06-06T18:00:00Z",
    type: "POST",
    engagement: { views: 5600, likes: 410, comments: 234, shares: 0 },
  },
];
