export const mockInfluencers = [
  {
    id: "inf-1",
    name: "Sarah Chen",
    platform: "YouTube",
    platformIcon: "🎬",
    handle: "@sarahcreates",
    followers: 245000,
    topics: ["content strategy", "creator economy", "social media marketing"],
    avgViews: 18500,
    avgEngagement: 4.2,
    avatarUrl: null,
    bio: "Teaching creators how to build sustainable businesses. 5 years in the creator economy.",
  },
  {
    id: "inf-2",
    name: "Marcus Rivera",
    platform: "TikTok",
    platformIcon: "🎵",
    handle: "@marcusrivera",
    followers: 890000,
    topics: ["content creation", "video editing", "storytelling"],
    avgViews: 125000,
    avgEngagement: 6.8,
    avatarUrl: null,
    bio: "Video editor turned creator. Helping you tell better stories in 60 seconds.",
  },
  {
    id: "inf-3",
    name: "Alex Thompson",
    platform: "Instagram",
    platformIcon: "📸",
    handle: "@alexthompson",
    followers: 156000,
    topics: ["personal branding", "content strategy", "instagram growth"],
    avgViews: 32000,
    avgEngagement: 3.9,
    avatarUrl: null,
    bio: "Brand strategist. Grew 3 brands from 0 to 100K. Sharing what works.",
  },
  {
    id: "inf-4",
    name: "Jamie Okafor",
    platform: "LinkedIn",
    platformIcon: "💼",
    handle: "jamie-okafor",
    followers: 52000,
    topics: ["b2b content", "thought leadership", "linkedin growth"],
    avgViews: 8500,
    avgEngagement: 5.1,
    avatarUrl: null,
    bio: "B2B content that doesn't put people to sleep. VP Marketing turned creator coach.",
  },
  {
    id: "inf-5",
    name: "Priya Sharma",
    platform: "Substack",
    platformIcon: "📝",
    handle: "priya-writes",
    followers: 28000,
    topics: ["newsletter growth", "writing", "creator tools"],
    avgViews: 4200,
    avgEngagement: 7.3,
    avatarUrl: null,
    bio: "Writing about writing. 28K subscribers in 18 months. No shortcuts.",
  },
  {
    id: "inf-6",
    name: "David Kim",
    platform: "Facebook",
    platformIcon: "👤",
    handle: "davidkimcreator",
    followers: 340000,
    topics: ["community building", "facebook groups", "creator monetization"],
    avgViews: 45000,
    avgEngagement: 3.2,
    avatarUrl: null,
    bio: "Built a 200K member community on Facebook. Teaching group growth strategies.",
  },
];

export const mockConnectedAccounts = [
  { id: "acc-1", platform: "YouTube", platformIcon: "🎬", handle: "@bedford-demo", status: "connected", followers: 1250 },
  { id: "acc-2", platform: "Instagram", platformIcon: "📸", handle: "@bedford.demo", status: "connected", followers: 3400 },
  { id: "acc-3", platform: "TikTok", platformIcon: "🎵", handle: "@bedforddemo", status: "connected", followers: 780 },
  { id: "acc-4", platform: "Facebook", platformIcon: "👤", handle: "Bedford Demo Page", status: "connected", followers: 2100 },
];

export const mockPosts = [
  {
    id: "post-1",
    title: "5 Tips for Growing Your Creator Business",
    platform: "YouTube",
    platformIcon: "🎬",
    publishedAt: "2026-06-01T14:00:00Z",
    type: "VIDEO",
    engagement: { views: 12400, likes: 890, comments: 156, shares: 0 },
  },
  {
    id: "post-2",
    title: "Behind the scenes of our content workshop",
    platform: "Instagram",
    platformIcon: "📸",
    publishedAt: "2026-06-03T10:30:00Z",
    type: "POST",
    engagement: { views: 8200, likes: 1240, comments: 89, shares: 234 },
  },
  {
    id: "post-3",
    title: "Creator tools you need in 2026",
    platform: "TikTok",
    platformIcon: "🎵",
    publishedAt: "2026-06-05T16:00:00Z",
    type: "VIDEO",
    engagement: { views: 45600, likes: 3200, comments: 412, shares: 1890 },
  },
  {
    id: "post-4",
    title: "How we train the next generation of creators",
    platform: "Facebook",
    platformIcon: "👤",
    publishedAt: "2026-06-02T09:00:00Z",
    type: "POST",
    engagement: { views: 3400, likes: 245, comments: 67, shares: 0 },
  },
  {
    id: "post-5",
    title: "The creator economy is broken. Here's how we fix it.",
    platform: "YouTube",
    platformIcon: "🎬",
    publishedAt: "2026-05-28T12:00:00Z",
    type: "VIDEO",
    engagement: { views: 28900, likes: 2100, comments: 389, shares: 0 },
  },
  {
    id: "post-6",
    title: "Day in the life of a content creator student",
    platform: "Instagram",
    platformIcon: "📸",
    publishedAt: "2026-06-07T11:00:00Z",
    type: "REELS",
    engagement: { views: 15300, likes: 2890, comments: 201, shares: 567 },
  },
  {
    id: "post-7",
    title: "What nobody tells you about going viral",
    platform: "TikTok",
    platformIcon: "🎵",
    publishedAt: "2026-06-08T15:30:00Z",
    type: "VIDEO",
    engagement: { views: 92300, likes: 8400, comments: 1230, shares: 4500 },
  },
  {
    id: "post-8",
    title: "Community AMA: Ask our top creators anything",
    platform: "Facebook",
    platformIcon: "👤",
    publishedAt: "2026-06-06T18:00:00Z",
    type: "POST",
    engagement: { views: 5600, likes: 410, comments: 234, shares: 0 },
  },
];
